.default-settings:
  only:
    refs:
      - master
      - /-stable/
      - merge-requests
      - tags@gitlab-org/gitlab-ce
      - tags@gitlab-org/gitlab-ee
      - tags@gitlab/gitlabhq
      - tags@gitlab/gitlab-ee

.dedicated-runner:
  extends: .default-settings
  retry:
    max: 1 # This is confusing but this means "2 runs at max".
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure
  tags:
    - gitlab-org

.dedicated-runner-with-cache:
  extends: .dedicated-runner
  cache:
    key: "debian-stretch-ruby-2.5.3-node-10.x"
    paths:
      - vendor/ruby
      - .yarn-cache/
      - vendor/gitaly-ruby

.dedicated-runner-code-diff:
  extends: .dedicated-runner-with-cache
  only:
    changes:
      - app/*
      - bin/*
      - config/*
      - db/*
      - ee/*
      - fixtures/*
      - lib/*
      - public/*
      - rubocop/*
      - spec/*
      - symbol/*
      - vendor/*
      - "*.{erb,haml,lock,js,json,rake,ru,png,rb,scss,svg,vue,yml}"
      - "**/*.{erb,haml,lock,js,json,rake,ru,png,rb,scss,svg,vue,yml}"
      - "*_VERSION"
      - Gemfile
      - Rakefile

.dedicated-runner-qa-diff:
  extends: .dedicated-runner-with-cache
  only:
    changes:
      - app/*
      - bin/*
      - config/*
      - db/*
      - ee/*
      - fixtures/*
      - lib/*
      - public/*
      - rubocop/*
      - spec/*
      - symbol/*
      - vendor/*
      - "*.{erb,haml,lock,js,json,rake,ru,png,rb,scss,svg,vue,yml}"
      - "**/*.{erb,haml,lock,js,json,rake,ru,png,rb,scss,svg,vue,yml}"
      - "*_VERSION"
      - qa/*
      - Gemfile
      - Rakefile

.dedicated-runner-code-diff-pull:
  extends: .dedicated-runner-code-diff
  cache:
    policy: pull
  stage: test

.dedicated-runner-code-diff-pull-no-db:
  extends: .dedicated-runner-code-diff-pull
  variables:
    SETUP_DB: "false"

.single-script-job-dedicated-runner:
  extends: .dedicated-runner
  image: ruby:2.5-alpine
  stage: test
  cache: {}
  dependencies: []
  variables:
    GIT_STRATEGY: none
  before_script:
    # We don't clone the repo by using GIT_STRATEGY: none and only download the
    # single script we need here so it's much faster than cloning.
    - export SCRIPT_NAME="${SCRIPT_NAME:-$CI_JOB_NAME}"
    - apk add --update openssl
    - wget $CI_PROJECT_URL/raw/$CI_COMMIT_SHA/scripts/$SCRIPT_NAME
    - chmod 755 $(basename $SCRIPT_NAME)
