# Insurance in case a gem needed by one of our releases gets yanked from
# rubygems.org in the future.
cache gems:
  extends: .dedicated-runner-code-diff-pull-no-db
  script:
    - bundle package --all --all-platforms
  artifacts:
    paths:
      - vendor/cache
  only:
    refs:
    - master@gitlab-org/gitlab-ce
    - master@gitlab-org/gitlab-ee
    - tags
  dependencies:
    - setup-test-env

gitlab_git_test:
  extends: .dedicated-runner-code-diff
  variables:
    SETUP_DB: "false"
  before_script: []
  dependencies: []
  cache: {}
  script:
    - spec/support/prepare-gitlab-git-test-for-commit --check-for-changes

no_ee_check:
  extends: .dedicated-runner-code-diff
  variables:
    SETUP_DB: "false"
  before_script: []
  dependencies: []
  cache: {}
  script:
    - scripts/no-ee-check
  only:
    refs:
    - merge-requests

